const baseGenre = {
  palette: { bg: '#11100D', ink: '#F1E7D2', accent: '#E8B200', muted: '#9B927F', leak: '#F08A38', cool: '#2A6F80' },
  dossierMood: 'Palette atelier, lisible et adaptable.',
  scoreLabels: ['scenario', 'mise en scene', 'emotion'],
  beat: { label: 'Le Moment', icon: 'star' },
  archetype: 'Film qui reste, meme apres le generique',
  lexicon: ['plan', 'trace', 'moment'],
  dossierLabels: ['Ouverture', 'Ce qui tient', 'Ce qui manque', 'Focus', 'Recap'],
  dossierKickers: ['Ouverture critique', 'Ce qui tient', 'Ce qui manque', 'Focus', 'Recap express'],
  dossierHeadlines: [
    'Ce que le film promet vraiment',
    'Ce qui donne envie de croire au film',
    'La ou le film perd un peu sa ligne',
    'Le moment qui concentre tout',
    'La critique en une minute',
  ],
  ficheHeadlines: ['Infos', 'Scores', 'Extraits', 'Comparaison', 'Resume'],
  feuilletonLabels: ['Avant', 'Pendant', 'Le Moment', 'Apres', 'Archetype'],
  prompt: {
    pitch: 'Un pitch en quelques lignes, avec ton angle critique plutot qu un resume automatique.',
    shortNote: 'La note courte qui donne le ton de la critique.',
    worksText: 'Ce que le film tient vraiment: une idee de mise en scene, un rythme, une emotion. Tu peux mettre un passage "entre guillemets" pour le faire ressortir.',
    blocksText: 'Ce qui reste moins net: une faiblesse, une frustration, un choix qui limite le film.',
    highlightTitle: 'Ce que je retiens',
    highlightText: 'Un motif, une scene, une idee ou une sensation que tu veux mettre au centre.',
    quickTake: 'A voir pour son atmosphere, son geste, ou ce qu il laisse apres le generique.',
    cta: 'Tu l as vu ? Dis-moi ce que tu en as pense.',
    works: ['Une idee de mise en scene qui tient.', 'Un rythme qui sert le film.', 'Une emotion ou une surprise qui reste.'],
    blocks: ['Un passage moins tenu.', 'Une idee qui aurait merite plus de place.', 'Une limite qui nuance la note.'],
    sceneQuote: 'La scene qui resume le film en une image.',
    verdict: 'Une phrase finale, nette, partageable.',
    comparisonTitle: 'un film voisin',
    comparison: 'Tu peux situer le film par proximite: meme energie, meme tension, meme plaisir.',
    avant: 'Ton attente avant d entrer en salle.',
    pendant: 'Ce que tu as ressenti pendant la projection.',
    apres: 'Ce que tu gardes du film en sortant.',
    caption1: 'Un detail de jeu, de cadre, ou de rythme.',
    caption2: 'Une image qui raconte ton ressenti.',
  },
};

const genre = (config) => ({
  ...baseGenre,
  ...config,
  palette: { ...baseGenre.palette, ...config.palette },
  beat: { ...baseGenre.beat, ...config.beat },
  prompt: { ...baseGenre.prompt, ...config.prompt },
});

export const REVIEW_GENRES = {
  Action: genre({
    palette: { bg: '#17100D', ink: '#F2E4CD', accent: '#D86D2F', muted: '#A08A72', leak: '#F09A3D', cool: '#446E73' },
    dossierMood: 'Ambre brule, mouvement, impact et poussiere.',
    scoreLabels: ['impact', 'rythme', 'lisibilite'],
    beat: { label: 'Le Choc', icon: 'blast' },
    archetype: 'Action tendue, muscles serres et sourire coupable',
    lexicon: ['impact', 'poursuite', 'detonation'],
    dossierLabels: ['Briefing', 'Impact', 'Angle mort', 'Cascade', 'Extraction'],
    dossierKickers: ['Briefing tactique', 'Zones d impact', 'Angle mort', 'Cascade centrale', 'Extraction'],
    dossierHeadlines: ['La mission que le film se donne', 'Ce qui frappe fort et juste', 'La ou l energie se disperse', 'La sequence qui encaisse tout', 'Debrief en une minute'],
    ficheHeadlines: ['Brief', 'Jauge', 'Impacts', 'Si tu veux du meme souffle', 'Verdict'],
    feuilletonLabels: ['Compte a rebours', 'Dans l impact', 'Le Choc', 'Retour au calme', 'Profil'],
    prompt: {
      pitch: 'Quel est l objectif, qui appuie sur l accelerateur, et pourquoi l action compte au-dela du bruit ?',
      worksText: 'Liste les impacts: lisibilite des scenes, rythme des coups, tension physique, plaisir de cascade.',
      blocksText: 'Repere les pertes d energie: action confuse, enjeu trop mince, climax qui patine.',
      highlightTitle: 'La cascade qui fait foi',
      quickTake: 'Pour l energie, l impact, et cette facon de transformer le chaos en plaisir net.',
    },
  }),
  Animation: genre({
    palette: { bg: '#D8D7B7', ink: '#191A14', accent: '#5E9F7D', muted: '#6D6E58', leak: '#F0C66E', cool: '#6FA6B2' },
    dossierMood: 'Couleurs patinees, douceur tactile, image qui respire.',
    scoreLabels: ['univers', 'rythme', 'coeur'],
    beat: { label: 'La Magie', icon: 'spark' },
    archetype: 'Animation sensible, enfance et cinema main dans la main',
    lexicon: ['texture', 'elan', 'merveille'],
    dossierLabels: ['Croquis', 'Mouvement', 'Faux pli', 'Planche', 'Album'],
    dossierKickers: ['Carnet de croquis', 'Ce qui prend vie', 'Faux pli', 'Planche maitresse', 'Album final'],
    dossierHeadlines: ['L univers qui s ouvre', 'Ce qui prend vie a limage', 'La ou le charme se froisse', 'Le dessin qui resume tout', 'La magie en une minute'],
    ficheHeadlines: ['Atelier', 'Jauges', 'Images', 'Si tu aimes ces mondes', 'Souvenir'],
    feuilletonLabels: ['Premiere esquisse', 'Image par image', 'La Magie', 'Derniere couleur', 'Profil'],
    prompt: {
      worksText: 'Parle des textures, de la fluidite, de l imagination visuelle et de ce que le film reveille.',
      blocksText: 'Note ce qui reste plus automatique: gag attendu, rythme trop sage, emotion forcee.',
      highlightTitle: 'La planche qui reste',
    },
  }),
  Aventure: genre({
    palette: { bg: '#162018', ink: '#F3E8CC', accent: '#D9A441', muted: '#9B9178', leak: '#C26B35', cool: '#2D7569' },
    dossierMood: 'Carte usee, verts profonds, or de fin d apres-midi.',
    scoreLabels: ['souffle', 'decouverte', 'periple'],
    beat: { label: 'Le Cap', icon: 'compass' },
    archetype: 'Aventure grand format, envie de repartir avant le noir salle',
    lexicon: ['carte', 'cap', 'horizon'],
    dossierLabels: ['Carte', 'Tresors', 'Sables mouvants', 'Horizon', 'Journal'],
    dossierKickers: ['Carte du voyage', 'Tresors trouves', 'Sables mouvants', 'Horizon cle', 'Journal de bord'],
    dossierHeadlines: ['La promesse du depart', 'Ce que le voyage revele', 'La ou la route s allonge', 'Le paysage qui raconte tout', 'Le periple en une minute'],
    ficheHeadlines: ['Carte', 'Boussole', 'Images', 'Prochaine expedition', 'Retour'],
    feuilletonLabels: ['Avant le depart', 'Sur la piste', 'Le Cap', 'Retour de voyage', 'Profil'],
  }),
  Biopic: genre({
    palette: { bg: '#E3D7C6', ink: '#211B17', accent: '#8F5F3D', muted: '#6F6258', leak: '#C89B6A', cool: '#556C79' },
    dossierMood: 'Archives chaudes, portrait intime, papier date.',
    scoreLabels: ['incarnation', 'epoque', 'point de vue'],
    beat: { label: 'Le Portrait', icon: 'portrait' },
    archetype: 'Biopic habite, entre archive et vertige intime',
    lexicon: ['archive', 'portrait', 'legende'],
    dossierLabels: ['Archive', 'Incarnation', 'Zone floue', 'Portrait', 'Legende'],
    dossierKickers: ['Ouverture des archives', 'Incarnation', 'Zone floue', 'Portrait central', 'Legende finale'],
    dossierHeadlines: ['Ce que le film choisit de raconter', 'Ce qui donne chair a la legende', 'La ou le portrait se fige', 'Le geste qui revele la personne', 'La vie en une minute'],
    ficheHeadlines: ['Archive', 'Mesures', 'Portraits', 'Si ce destin te parle', 'Legende'],
    feuilletonLabels: ['Avant le portrait', 'Face a la legende', 'Le Portrait', 'Apres l archive', 'Profil'],
  }),
  'Comédie': genre({
    palette: { bg: '#F2D66B', ink: '#181512', accent: '#E94F37', muted: '#625A3B', leak: '#FCA83E', cool: '#248C83' },
    dossierMood: 'Blocs francs, typo joueuse, couleurs qui claquent.',
    scoreLabels: ['rire', 'rythme', 'coeur'],
    beat: { label: 'Le Fou Rire', icon: 'spark' },
    archetype: 'Comedie solaire, sourire coince aux levres',
    lexicon: ['vanne', 'tempo', 'replique'],
    dossierLabels: ['Setup', 'Timing', 'Bide', 'Replique', 'Encore'],
    dossierKickers: ['Mise en place', 'Timing gagnant', 'Bide ou flottement', 'Replique culte', 'Encore ?'],
    dossierHeadlines: ['La blague que le film installe', 'Ce qui fait mouche', 'La ou le rire se tasse', 'La replique qui gagne la salle', 'Le rire en une minute'],
    ficheHeadlines: ['Setup', 'Jauges', 'Gags', 'Si tu veux rire pareil', 'Chute'],
    feuilletonLabels: ['Avant la vanne', 'Pendant le gag', 'Le Fou Rire', 'Apres la chute', 'Profil'],
  }),
  'Comédie noire': genre({
    palette: { bg: '#151210', ink: '#F0E6D7', accent: '#A8D05F', muted: '#A19687', leak: '#6C8E3F', cool: '#743D4B' },
    dossierMood: 'Humour acide, noirs mats, vert toxique.',
    scoreLabels: ['acidite', 'malaise', 'precision'],
    beat: { label: 'Le Rire Jaune', icon: 'smirk' },
    archetype: 'Comedie noire, rire coince juste au bord du malaise',
    lexicon: ['venin', 'malaise', 'chute'],
    dossierLabels: ['Piege', 'Venin', 'Malaise', 'Chute', 'Aftertaste'],
    dossierKickers: ['Piege comique', 'Dose de venin', 'Malaise controle', 'Chute noire', 'Aftertaste'],
    dossierHeadlines: ['La mechancete que le film assume', 'Ce qui pique vraiment', 'La ou le venin se dilue', 'La scene qui fait rire de travers', 'Le malaise en une minute'],
    ficheHeadlines: ['Piege', 'Dosage', 'Preuves', 'Meme venin', 'Chute'],
    feuilletonLabels: ['Avant le piege', 'Dans le malaise', 'Le Rire Jaune', 'Apres le venin', 'Profil'],
  }),
  Documentaire: genre({
    palette: { bg: '#ECE7DC', ink: '#171A1D', accent: '#2F7C8F', muted: '#6E777A', leak: '#B6A36D', cool: '#466A5C' },
    dossierMood: 'Carnet terrain, lignes claires, matiere du reel.',
    scoreLabels: ['regard', 'matiere', 'necessite'],
    beat: { label: 'La Preuve', icon: 'lens' },
    archetype: 'Documentaire qui regarde longtemps, sans decorer le reel',
    lexicon: ['terrain', 'temoin', 'preuve'],
    dossierLabels: ['Terrain', 'Temoins', 'Angles morts', 'Preuve', 'Constat'],
    dossierKickers: ['Carnet de terrain', 'Temoins solides', 'Angles morts', 'Preuve sensible', 'Constat final'],
    dossierHeadlines: ['Ce que le film va chercher dans le reel', 'Ce qui donne du poids au regard', 'La ou l enquete manque un angle', 'L image qui vaut preuve', 'Le constat en une minute'],
    ficheHeadlines: ['Terrain', 'Indicateurs', 'Documents', 'Meme regard', 'Constat'],
    feuilletonLabels: ['Avant le terrain', 'Face au reel', 'La Preuve', 'Apres le constat', 'Profil'],
  }),
  Drame: genre({
    palette: { bg: '#E9D8BB', ink: '#211A15', accent: '#B2673B', muted: '#695748', leak: '#F0A24B', cool: '#587C86' },
    dossierMood: 'Marges larges, grain chaud, respiration de magazine.',
    scoreLabels: ['emotion', 'ecriture', 'justesse'],
    beat: { label: 'La Faille', icon: 'drop' },
    archetype: 'Drame sensible, retour silencieux dans le metro',
    lexicon: ['faille', 'silence', 'cicatrice'],
    dossierLabels: ['Faille', 'Tension', 'Trop-plein', 'Silence', 'Trace'],
    dossierKickers: ['Ouverture de la faille', 'Tension juste', 'Trop-plein', 'Silence central', 'Trace finale'],
    dossierHeadlines: ['La blessure que le film approche', 'Ce qui sonne juste', 'La ou l emotion insiste trop', 'Le silence qui dit tout', 'La trace en une minute'],
    ficheHeadlines: ['Situation', 'Jauges', 'Fragments', 'Meme intensite', 'Trace'],
    feuilletonLabels: ['Avant la faille', 'Dans la tension', 'La Faille', 'Apres le silence', 'Profil'],
  }),
  Familial: genre({
    palette: { bg: '#F0E1B9', ink: '#231B13', accent: '#3F9E8F', muted: '#766A55', leak: '#F2B45E', cool: '#8C6AA8' },
    dossierMood: 'Chaleur collective, couleurs rondes, lecture immediate.',
    scoreLabels: ['partage', 'douceur', 'energie'],
    beat: { label: 'Le Cocon', icon: 'home' },
    archetype: 'Film familial doudou, simple sans etre petit',
    lexicon: ['tribu', 'cocon', 'passage'],
    dossierLabels: ['Cocon', 'Tribu', 'Fausse note', 'Image-doudou', 'Sortie'],
    dossierKickers: ['Entree dans le cocon', 'Plaisir partage', 'Fausse note', 'Image-doudou', 'Sortie famille'],
    dossierHeadlines: ['La promesse pour tous les ages', 'Ce qui rassemble vraiment', 'La ou l equilibre se perd', 'L image qui fait doudou', 'La sortie en une minute'],
    ficheHeadlines: ['Cocon', 'Jauges', 'Moments', 'Prochaine sortie', 'Souvenir'],
    feuilletonLabels: ['Avant le cocon', 'Avec la tribu', 'Le Cocon', 'Apres la sortie', 'Profil'],
  }),
  Fantastique: genre({
    palette: { bg: '#17131E', ink: '#F0E8F6', accent: '#9E6EE8', muted: '#A69AB2', leak: '#6CC0A8', cool: '#3D5A8C' },
    dossierMood: 'Brume violette, seuils et mystere latent.',
    scoreLabels: ['mystere', 'imaginaire', 'trouble'],
    beat: { label: 'Le Seuil', icon: 'portal' },
    archetype: 'Fantastique trouble, un pied dans le reel et l autre ailleurs',
    lexicon: ['seuil', 'sortilege', 'apparition'],
    dossierLabels: ['Seuil', 'Sortileges', 'Fissures', 'Apparition', 'Retour'],
    dossierKickers: ['Passage du seuil', 'Sortileges actifs', 'Fissures du monde', 'Apparition cle', 'Retour au reel'],
    dossierHeadlines: ['La regle du monde impossible', 'Ce qui enchante ou inquiete', 'La ou le mystere se dissipe', 'L apparition qui change tout', 'Le sortilege en une minute'],
    ficheHeadlines: ['Seuil', 'Jauges', 'Visions', 'Meme mystere', 'Retour'],
    feuilletonLabels: ['Avant le seuil', 'Dans l etrange', 'Le Seuil', 'Apres l apparition', 'Profil'],
  }),
  Historique: genre({
    palette: { bg: '#D9C9A8', ink: '#1F1B16', accent: '#8D6B36', muted: '#746954', leak: '#B55F3E', cool: '#4E6570' },
    dossierMood: 'Patine d archive, or ancien, gravite chronologique.',
    scoreLabels: ['epoque', 'ampleur', 'incarnation'],
    beat: { label: 'La Fresque', icon: 'column' },
    archetype: 'Historique ample, poussiere d archive et chair humaine',
    lexicon: ['archive', 'fresque', 'chronique'],
    dossierLabels: ['Chronique', 'Fresque', 'Anachronie', 'Tableau', 'Memoire'],
    dossierKickers: ['Chronique ouverte', 'Fresque vivante', 'Anachronies', 'Tableau cle', 'Memoire finale'],
    dossierHeadlines: ['L epoque que le film recompose', 'Ce qui donne de l ampleur au passe', 'La ou la reconstitution pese', 'Le tableau qui traverse le temps', 'La memoire en une minute'],
    ficheHeadlines: ['Chronique', 'Jauges', 'Tableaux', 'Meme epoque', 'Memoire'],
    feuilletonLabels: ['Avant la fresque', 'Dans l epoque', 'La Fresque', 'Apres la memoire', 'Profil'],
  }),
  Musical: genre({
    palette: { bg: '#19131A', ink: '#FFF2D7', accent: '#F05AA6', muted: '#B9A7A9', leak: '#F6B64A', cool: '#3FA7C2' },
    dossierMood: 'Scene lumineuse, neons chauds, rythme de coulisses.',
    scoreLabels: ['numero', 'rythme', 'emotion'],
    beat: { label: 'Le Refrain', icon: 'music' },
    archetype: 'Musical qui reste dans la tete, meme quand la salle se rallume',
    lexicon: ['refrain', 'tempo', 'scene'],
    dossierLabels: ['Ouverture', 'Tempo', 'Fausse note', 'Numero', 'Rappel'],
    dossierKickers: ['Ouverture musicale', 'Tempo gagnant', 'Fausse note', 'Numero central', 'Rappel final'],
    dossierHeadlines: ['La promesse de scene', 'Ce qui trouve le bon tempo', 'La ou la chanson retombe', 'Le numero qui emporte tout', 'Le refrain en une minute'],
    ficheHeadlines: ['Scene', 'Jauges', 'Numeros', 'Meme tempo', 'Rappel'],
    feuilletonLabels: ['Avant le rideau', 'Dans le tempo', 'Le Refrain', 'Apres le rappel', 'Profil'],
  }),
  Policier: genre({
    palette: { bg: '#090B0D', ink: '#EEE7D8', accent: '#D64032', muted: '#908D86', leak: '#C9272D', cool: '#1F6F7C' },
    dossierMood: 'Cadre serre, contraste dur, accent rouge nerveux.',
    scoreLabels: ['indices', 'tension', 'resolution'],
    beat: { label: 'La Preuve', icon: 'clue' },
    archetype: 'Policier nocturne, indices sous la pluie et doute persistant',
    lexicon: ['indice', 'preuve', 'suspect'],
    dossierLabels: ['Scene', 'Indices', 'Fausse piste', 'Preuve', 'Cloture'],
    dossierKickers: ['Scene de depart', 'Indices concordants', 'Fausse piste', 'Piece a conviction', 'Cloture du dossier'],
    dossierHeadlines: ['L affaire que le film ouvre', 'Ce qui tient comme preuve', 'La ou l enquete perd sa piste', 'L indice qui fait basculer', 'Le dossier classe en une minute'],
    ficheHeadlines: ['Affaire', 'Preuves', 'Pieces', 'Meme enquete', 'Verdict'],
    feuilletonLabels: ['Avant l affaire', 'Sur la piste', 'La Preuve', 'Apres la revelation', 'Profil'],
    prompt: {
      worksText: 'Releve les preuves: atmosphere, indices, suspects, fausses pistes, resolution.',
      blocksText: 'Note les incoherences, raccourcis d enquete ou revelations trop faciles.',
      highlightTitle: 'La piece a conviction',
    },
  }),
  Romance: genre({
    palette: { bg: '#E9C9C9', ink: '#241717', accent: '#C9566F', muted: '#725157', leak: '#F1A4A8', cool: '#8C7088' },
    dossierMood: 'Lumiere douce, halation rose, emotion en suspension.',
    scoreLabels: ['alchimie', 'emotion', 'souvenir'],
    beat: { label: 'Le Frisson', icon: 'heart' },
    archetype: 'Romance en clair-obscur, sourire un peu triste',
    lexicon: ['regard', 'frisson', 'absence'],
    dossierLabels: ['Rencontre', 'Alchimie', 'Distance', 'Regard', 'Souvenir'],
    dossierKickers: ['Premiere rencontre', 'Alchimie visible', 'Distance', 'Regard decisif', 'Souvenir final'],
    dossierHeadlines: ['La promesse de rencontre', 'Ce qui fait battre le film', 'La ou l emotion s eloigne', 'Le regard qui suffit', 'Le souvenir en une minute'],
    ficheHeadlines: ['Rencontre', 'Jauges', 'Regards', 'Meme frisson', 'Souvenir'],
    feuilletonLabels: ['Avant la rencontre', 'Dans l alchimie', 'Le Frisson', 'Apres le regard', 'Profil'],
  }),
  Satire: genre({
    palette: { bg: '#F0E7C7', ink: '#1A1711', accent: '#C23B30', muted: '#6F664D', leak: '#E0B34F', cool: '#316B65' },
    dossierMood: 'Affiche mordante, rouge editorial, ironie propre.',
    scoreLabels: ['cible', 'mordant', 'precision'],
    beat: { label: 'La Piqûre', icon: 'pin' },
    archetype: 'Satire affutee, sourire poli et lame visible',
    lexicon: ['cible', 'piqure', 'masque'],
    dossierLabels: ['Cible', 'Mordant', 'Angle mort', 'Piqûre', 'Charge'],
    dossierKickers: ['Cible identifiee', 'Mordant', 'Angle mort', 'Piqûre nette', 'Charge finale'],
    dossierHeadlines: ['Ce que le film prend pour cible', 'Ce qui mord vraiment', 'La ou la charge rate son angle', 'La piqûre qui revele tout', 'La satire en une minute'],
    ficheHeadlines: ['Cible', 'Jauges', 'Piqûres', 'Meme mordant', 'Charge'],
    feuilletonLabels: ['Avant la charge', 'Dans la cible', 'La Piqûre', 'Apres le sourire', 'Profil'],
  }),
  'Science fiction': genre({
    palette: { bg: '#10151A', ink: '#E9F1EA', accent: '#56B6C2', muted: '#8EA0A0', leak: '#7FC7FF', cool: '#4651A8' },
    dossierMood: 'Cyan diffus, noirs spatiaux, texture de reve analogique.',
    scoreLabels: ['monde', 'idee', 'vertige'],
    beat: { label: 'Le Vertige', icon: 'orbit' },
    archetype: 'Science fiction reveuse, cerveau encore allume',
    lexicon: ['signal', 'orbite', 'paradoxe'],
    dossierLabels: ['Signal', 'Monde', 'Paradoxe', 'Orbites', 'Transmission'],
    dossierKickers: ['Signal initial', 'Monde construit', 'Paradoxe', 'Orbites cle', 'Transmission finale'],
    dossierHeadlines: ['L hypothese que le film lance', 'Ce qui construit un monde', 'La ou l idee se brouille', 'L image qui cree le vertige', 'La transmission en une minute'],
    ficheHeadlines: ['Signal', 'Jauges', 'Visions', 'Meme orbite', 'Transmission'],
    feuilletonLabels: ['Avant le signal', 'Dans le monde', 'Le Vertige', 'Apres l orbite', 'Profil'],
  }),
  Société: genre({
    palette: { bg: '#E6E0D4', ink: '#191B1E', accent: '#2D6CDF', muted: '#66707A', leak: '#D6843A', cool: '#3E7D6B' },
    dossierMood: 'Editorial contemporain, bleu franc, tension collective.',
    scoreLabels: ['regard', 'urgence', 'nuance'],
    beat: { label: 'Le Symptôme', icon: 'pulse' },
    archetype: 'Film de societe lucide, intime et collectif a la fois',
    lexicon: ['systeme', 'symptome', 'collectif'],
    dossierLabels: ['Constat', 'Systeme', 'Impasse', 'Symptôme', 'Debat'],
    dossierKickers: ['Constat social', 'Systeme visible', 'Impasse', 'Symptôme central', 'Debat final'],
    dossierHeadlines: ['Ce que le film observe de nous', 'Ce qui rend le collectif visible', 'La ou le propos se simplifie', 'Le symptôme qui raconte tout', 'Le debat en une minute'],
    ficheHeadlines: ['Constat', 'Jauges', 'Fragments', 'Meme urgence', 'Debat'],
    feuilletonLabels: ['Avant le constat', 'Dans le systeme', 'Le Symptôme', 'Apres le debat', 'Profil'],
  }),
  Thriller: genre({
    palette: { bg: '#0B1115', ink: '#EFE7D8', accent: '#D8483E', muted: '#9A9389', leak: '#B92732', cool: '#235A70' },
    dossierMood: 'Noirs tendus, rouge alerte, sensation de compte a rebours.',
    scoreLabels: ['tension', 'rythme', 'twist'],
    beat: { label: 'Le Twist', icon: 'bolt' },
    archetype: 'Thriller nerveux, 8h et un cafe apres',
    lexicon: ['menace', 'piste', 'twist'],
    dossierLabels: ['Menace', 'Pression', 'Faille', 'Twist', 'Sortie'],
    dossierKickers: ['Menace initiale', 'Pression constante', 'Faille du dispositif', 'Twist central', 'Sortie sous tension'],
    dossierHeadlines: ['La menace qui met le film en route', 'Ce qui serre vraiment la vis', 'La ou la tension fuit', 'Le twist qui redistribue tout', 'La tension en une minute'],
    ficheHeadlines: ['Menace', 'Jauges', 'Indices', 'Meme tension', 'Sortie'],
    feuilletonLabels: ['Avant la menace', 'Sous pression', 'Le Twist', 'Apres le choc', 'Profil'],
  }),
  default: baseGenre,
};

const ALIASES = {
  action: 'Action',
  animation: 'Animation',
  aventure: 'Aventure',
  adventure: 'Aventure',
  biopic: 'Biopic',
  biography: 'Biopic',
  biographie: 'Biopic',
  comedy: 'Comédie',
  comedie: 'Comédie',
  'comedie noire': 'Comédie noire',
  'black comedy': 'Comédie noire',
  documentaire: 'Documentaire',
  documentary: 'Documentaire',
  drame: 'Drame',
  drama: 'Drame',
  familial: 'Familial',
  family: 'Familial',
  fantastique: 'Fantastique',
  fantasy: 'Fantastique',
  historique: 'Historique',
  history: 'Historique',
  musical: 'Musical',
  policier: 'Policier',
  crime: 'Policier',
  detective: 'Policier',
  romance: 'Romance',
  satire: 'Satire',
  'science fiction': 'Science fiction',
  'science-fiction': 'Science fiction',
  'sci fi': 'Science fiction',
  'sci-fi': 'Science fiction',
  societe: 'Société',
  social: 'Société',
  thriller: 'Thriller',
};

export const REVIEW_FORMATS = [
  {
    id: 'dossier',
    name: 'Le Dossier',
    eyebrow: 'Magazine critique',
    description: 'Une critique longue, editorialisee, avec pitch, scene marquante et verdict.',
    slides: ['Couverture', 'Ouverture', 'Ce qui tient', 'Ce qui manque', 'Focus', 'Recap'],
  },
  {
    id: 'fiche',
    name: 'La Fiche Cine',
    eyebrow: 'Carte structuree',
    description: 'Une critique rapide a lire, pensee pour les notes, infos et comparaisons.',
    slides: ['Couverture', 'Infos', 'Scores', 'Extraits', 'Comparaison', 'Resume'],
  },
  {
    id: 'feuilleton',
    name: 'Le Feuilleton',
    eyebrow: 'Arc visuel',
    description: 'Un format photo-rich autour de ton experience avant, pendant et apres la seance.',
    slides: ['Couverture', 'Avant', 'Pendant', 'Beat de genre', 'Apres', 'Archetype'],
  },
];

export function normalizeReviewGenreName(value) {
  const clean = String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[_/]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();

  if (!clean) return 'default';
  if (ALIASES[clean]) return ALIASES[clean];
  const partial = Object.entries(ALIASES).find(([alias]) => clean.includes(alias));
  return partial?.[1] || 'default';
}

export function getReviewGenreConfig(genreName) {
  const normalized = normalizeReviewGenreName(genreName);
  return REVIEW_GENRES[normalized] || REVIEW_GENRES.default;
}
